module core_wrap (
    input  wire        clk,
    input  wire        rst,
    input  wire        dbg_prog,

    output wire        dbg_pause,
    output wire [31:0] dbg_pc,
    output wire        dbg_commit,
    output wire        dbg_pipe_busy,

    input  wire [7:0]  s_mmio_araddr,
    input  wire [2:0]  s_mmio_arprot,
    input  wire        s_mmio_arvalid,
    output wire        s_mmio_arready,
    output wire [31:0] s_mmio_rdata,
    output wire [1:0]  s_mmio_rresp,
    output wire        s_mmio_rvalid,
    input  wire        s_mmio_rready,
    input  wire [7:0]  s_mmio_awaddr,
    input  wire [2:0]  s_mmio_awprot,
    input  wire        s_mmio_awvalid,
    output wire        s_mmio_awready,
    input  wire [31:0] s_mmio_wdata,
    input  wire [3:0]  s_mmio_wstrb,
    input  wire        s_mmio_wvalid,
    output wire        s_mmio_wready,
    output wire [1:0]  s_mmio_bresp,
    output wire        s_mmio_bvalid,
    input  wire        s_mmio_bready,

    output wire        m_axis_tvalid,
    input  wire        m_axis_tready,
    output wire [31:0] m_axis_tdata,

    input  wire        s_axis_tvalid,
    output wire        s_axis_tready,
    input  wire [31:0] s_axis_tdata,
    input  wire [31:0] s_axis_level,

    output wire [31:0] m_imem_araddr,
    output wire [2:0]  m_imem_arprot,
    output wire        m_imem_arvalid,
    input  wire        m_imem_arready,
    input  wire [31:0] m_imem_rdata,
    input  wire [1:0]  m_imem_rresp,
    input  wire        m_imem_rvalid,
    output wire        m_imem_rready,
    output wire [31:0] m_imem_awaddr,
    output wire [2:0]  m_imem_awprot,
    output wire        m_imem_awvalid,
    input  wire        m_imem_awready,
    output wire [31:0] m_imem_wdata,
    output wire [3:0]  m_imem_wstrb,
    output wire        m_imem_wvalid,
    input  wire        m_imem_wready,
    input  wire [1:0]  m_imem_bresp,
    input  wire        m_imem_bvalid,
    output wire        m_imem_bready,

    output wire [31:0] m_dmem_araddr,
    output wire [2:0]  m_dmem_arprot,
    output wire        m_dmem_arvalid,
    input  wire        m_dmem_arready,
    input  wire [31:0] m_dmem_rdata,
    input  wire [1:0]  m_dmem_rresp,
    input  wire        m_dmem_rvalid,
    output wire        m_dmem_rready,
    output wire [31:0] m_dmem_awaddr,
    output wire [2:0]  m_dmem_awprot,
    output wire        m_dmem_awvalid,
    input  wire        m_dmem_awready,
    output wire [31:0] m_dmem_wdata,
    output wire [3:0]  m_dmem_wstrb,
    output wire        m_dmem_wvalid,
    input  wire        m_dmem_wready,
    input  wire [1:0]  m_dmem_bresp,
    input  wire        m_dmem_bvalid,
    output wire        m_dmem_bready
);

    core u_core(
        .clk             (clk             ),
        .rst             (rst             ),
        .dbg_prog        (dbg_prog        ),
        .dbg_pause       (dbg_pause       ),
        .dbg_pc          (dbg_pc          ),
        .dbg_commit      (dbg_commit      ),
        .dbg_pipe_busy   (dbg_pipe_busy   ),
        .s_mmio_araddr   (s_mmio_araddr   ),
        .s_mmio_arprot   (s_mmio_arprot   ),
        .s_mmio_arvalid  (s_mmio_arvalid  ),
        .s_mmio_arready  (s_mmio_arready  ),
        .s_mmio_rdata    (s_mmio_rdata    ),
        .s_mmio_rresp    (s_mmio_rresp    ),
        .s_mmio_rvalid   (s_mmio_rvalid   ),
        .s_mmio_rready   (s_mmio_rready   ),
        .s_mmio_awaddr   (s_mmio_awaddr   ),
        .s_mmio_awprot   (s_mmio_awprot   ),
        .s_mmio_awvalid  (s_mmio_awvalid  ),
        .s_mmio_awready  (s_mmio_awready  ),
        .s_mmio_wdata    (s_mmio_wdata    ),
        .s_mmio_wstrb    (s_mmio_wstrb    ),
        .s_mmio_wvalid   (s_mmio_wvalid   ),
        .s_mmio_wready   (s_mmio_wready   ),
        .s_mmio_bresp    (s_mmio_bresp    ),
        .s_mmio_bvalid   (s_mmio_bvalid   ),
        .s_mmio_bready   (s_mmio_bready   ),
        .m_axis_tvalid   (m_axis_tvalid   ),
        .m_axis_tready   (m_axis_tready   ),
        .m_axis_tdata    (m_axis_tdata    ),
        .s_axis_tvalid   (s_axis_tvalid   ),
        .s_axis_tready   (s_axis_tready   ),
        .s_axis_tdata    (s_axis_tdata    ),
        .s_axis_level    (s_axis_level    ),
        .m_imem_araddr   (m_imem_araddr   ),
        .m_imem_arprot   (m_imem_arprot   ),
        .m_imem_arvalid  (m_imem_arvalid  ),
        .m_imem_arready  (m_imem_arready  ),
        .m_imem_rdata    (m_imem_rdata    ),
        .m_imem_rresp    (m_imem_rresp    ),
        .m_imem_rvalid   (m_imem_rvalid   ),
        .m_imem_rready   (m_imem_rready   ),
        .m_imem_awaddr   (m_imem_awaddr   ),
        .m_imem_awprot   (m_imem_awprot   ),
        .m_imem_awvalid  (m_imem_awvalid  ),
        .m_imem_awready  (m_imem_awready  ),
        .m_imem_wdata    (m_imem_wdata    ),
        .m_imem_wstrb    (m_imem_wstrb    ),
        .m_imem_wvalid   (m_imem_wvalid   ),
        .m_imem_wready   (m_imem_wready   ),
        .m_imem_bresp    (m_imem_bresp    ),
        .m_imem_bvalid   (m_imem_bvalid   ),
        .m_imem_bready   (m_imem_bready   ),
        .m_dmem_araddr   (m_dmem_araddr   ),
        .m_dmem_arprot   (m_dmem_arprot   ),
        .m_dmem_arvalid  (m_dmem_arvalid  ),
        .m_dmem_arready  (m_dmem_arready  ),
        .m_dmem_rdata    (m_dmem_rdata    ),
        .m_dmem_rresp    (m_dmem_rresp    ),
        .m_dmem_rvalid   (m_dmem_rvalid   ),
        .m_dmem_rready   (m_dmem_rready   ),
        .m_dmem_awaddr   (m_dmem_awaddr   ),
        .m_dmem_awprot   (m_dmem_awprot   ),
        .m_dmem_awvalid  (m_dmem_awvalid  ),
        .m_dmem_awready  (m_dmem_awready  ),
        .m_dmem_wdata    (m_dmem_wdata    ),
        .m_dmem_wstrb    (m_dmem_wstrb    ),
        .m_dmem_wvalid   (m_dmem_wvalid   ),
        .m_dmem_wready   (m_dmem_wready   ),
        .m_dmem_bresp    (m_dmem_bresp    ),
        .m_dmem_bvalid   (m_dmem_bvalid   ),
        .m_dmem_bready   (m_dmem_bready   )
    );

endmodule
